// Code generated by protoc-gen-go. DO NOT EDIT.
// source: route_guide.proto

package routeguide

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Points are represented as latitude-longitude pairs in the E7 representation
// (degrees multiplied by 10**7 and rounded to the nearest integer).
// Latitudes should be in the range +/- 90 degrees and longitude should be in
// the range +/- 180 degrees (inclusive).
type Point struct {
	Latitude             int32    `protobuf:"varint,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            int32    `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7d679f20da65b7b, []int{0}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetLatitude() int32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Point) GetLongitude() int32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

// A latitude-longitude rectangle, represented as two diagonally opposite
// points "lo" and "hi".
type Rectangle struct {
	// One corner of the rectangle.
	Lo *Point `protobuf:"bytes,1,opt,name=lo,proto3" json:"lo,omitempty"`
	// The other corner of the rectangle.
	Hi                   *Point   `protobuf:"bytes,2,opt,name=hi,proto3" json:"hi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rectangle) Reset()         { *m = Rectangle{} }
func (m *Rectangle) String() string { return proto.CompactTextString(m) }
func (*Rectangle) ProtoMessage()    {}
func (*Rectangle) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7d679f20da65b7b, []int{1}
}

func (m *Rectangle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rectangle.Unmarshal(m, b)
}
func (m *Rectangle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rectangle.Marshal(b, m, deterministic)
}
func (m *Rectangle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rectangle.Merge(m, src)
}
func (m *Rectangle) XXX_Size() int {
	return xxx_messageInfo_Rectangle.Size(m)
}
func (m *Rectangle) XXX_DiscardUnknown() {
	xxx_messageInfo_Rectangle.DiscardUnknown(m)
}

var xxx_messageInfo_Rectangle proto.InternalMessageInfo

func (m *Rectangle) GetLo() *Point {
	if m != nil {
		return m.Lo
	}
	return nil
}

func (m *Rectangle) GetHi() *Point {
	if m != nil {
		return m.Hi
	}
	return nil
}

// A feature names something at a given point.
//
// If a feature could not be named, the name is empty.
type Feature struct {
	// The name of the feature.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The point where the feature is detected.
	Location             *Point   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7d679f20da65b7b, []int{2}
}

func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (m *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(m, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Feature) GetLocation() *Point {
	if m != nil {
		return m.Location
	}
	return nil
}

// A RouteNote is a message sent while at a given point.
type RouteNote struct {
	// The location from which the message is sent.
	Location *Point `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	// The message to be sent.
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteNote) Reset()         { *m = RouteNote{} }
func (m *RouteNote) String() string { return proto.CompactTextString(m) }
func (*RouteNote) ProtoMessage()    {}
func (*RouteNote) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7d679f20da65b7b, []int{3}
}

func (m *RouteNote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteNote.Unmarshal(m, b)
}
func (m *RouteNote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteNote.Marshal(b, m, deterministic)
}
func (m *RouteNote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteNote.Merge(m, src)
}
func (m *RouteNote) XXX_Size() int {
	return xxx_messageInfo_RouteNote.Size(m)
}
func (m *RouteNote) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteNote.DiscardUnknown(m)
}

var xxx_messageInfo_RouteNote proto.InternalMessageInfo

func (m *RouteNote) GetLocation() *Point {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *RouteNote) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// A RouteSummary is received in response to a RecordRoute rpc.
//
// It contains the number of individual points received, the number of
// detected features, and the total distance covered as the cumulative sum of
// the distance between each point.
type RouteSummary struct {
	// The number of points received.
	PointCount int32 `protobuf:"varint,1,opt,name=point_count,json=pointCount,proto3" json:"point_count,omitempty"`
	// The number of known features passed while traversing the route.
	FeatureCount int32 `protobuf:"varint,2,opt,name=feature_count,json=featureCount,proto3" json:"feature_count,omitempty"`
	// The distance covered in metres.
	Distance int32 `protobuf:"varint,3,opt,name=distance,proto3" json:"distance,omitempty"`
	// The duration of the traversal in seconds.
	ElapsedTime          int32    `protobuf:"varint,4,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteSummary) Reset()         { *m = RouteSummary{} }
func (m *RouteSummary) String() string { return proto.CompactTextString(m) }
func (*RouteSummary) ProtoMessage()    {}
func (*RouteSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7d679f20da65b7b, []int{4}
}

func (m *RouteSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteSummary.Unmarshal(m, b)
}
func (m *RouteSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteSummary.Marshal(b, m, deterministic)
}
func (m *RouteSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteSummary.Merge(m, src)
}
func (m *RouteSummary) XXX_Size() int {
	return xxx_messageInfo_RouteSummary.Size(m)
}
func (m *RouteSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteSummary.DiscardUnknown(m)
}

var xxx_messageInfo_RouteSummary proto.InternalMessageInfo

func (m *RouteSummary) GetPointCount() int32 {
	if m != nil {
		return m.PointCount
	}
	return 0
}

func (m *RouteSummary) GetFeatureCount() int32 {
	if m != nil {
		return m.FeatureCount
	}
	return 0
}

func (m *RouteSummary) GetDistance() int32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *RouteSummary) GetElapsedTime() int32 {
	if m != nil {
		return m.ElapsedTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Point)(nil), "routeguide.Point")
	proto.RegisterType((*Rectangle)(nil), "routeguide.Rectangle")
	proto.RegisterType((*Feature)(nil), "routeguide.Feature")
	proto.RegisterType((*RouteNote)(nil), "routeguide.RouteNote")
	proto.RegisterType((*RouteSummary)(nil), "routeguide.RouteSummary")
}

func init() { proto.RegisterFile("route_guide.proto", fileDescriptor_b7d679f20da65b7b) }

var fileDescriptor_b7d679f20da65b7b = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0xbe, 0x8d, 0x77, 0x5e, 0x33, 0xad, 0x48, 0x47, 0x84, 0x10, 0x05, 0xbd, 0xf8, 0x72, 0x2f,
	0x86, 0x72, 0x82, 0x4f, 0x3e, 0xe8, 0x59, 0x5a, 0x1f, 0x44, 0x6a, 0xec, 0x7b, 0x59, 0x93, 0x69,
	0xba, 0xb0, 0xc9, 0x86, 0x64, 0x57, 0xea, 0x5f, 0xf0, 0xd5, 0x3f, 0x2c, 0xd9, 0x24, 0x6d, 0x8a,
	0x29, 0xf7, 0xb6, 0xf3, 0xcd, 0x37, 0xdf, 0xcc, 0x7c, 0xc3, 0xc2, 0xb4, 0x54, 0x46, 0xd3, 0x26,
	0x35, 0x22, 0xa1, 0xb0, 0x28, 0x95, 0x56, 0x08, 0x16, 0xb2, 0x48, 0xf0, 0x09, 0xae, 0x56, 0x4a,
	0xe4, 0x1a, 0x7d, 0x18, 0x49, 0xae, 0x85, 0x36, 0x09, 0x79, 0xec, 0x35, 0xbb, 0xbd, 0x8a, 0x0e,
	0x31, 0xbe, 0x04, 0x57, 0xaa, 0x3c, 0x6d, 0x92, 0x8e, 0x4d, 0x1e, 0x81, 0xe0, 0x3b, 0xb8, 0x11,
	0xc5, 0x9a, 0xe7, 0xa9, 0x24, 0xbc, 0x01, 0x47, 0x2a, 0x2b, 0x30, 0xbe, 0x9b, 0x86, 0xc7, 0x46,
	0xa1, 0xed, 0x12, 0x39, 0x52, 0xd5, 0x94, 0x9d, 0xb0, 0x32, 0xc3, 0x94, 0x9d, 0x08, 0xbe, 0xc2,
	0xf5, 0x82, 0xb8, 0x36, 0x25, 0x21, 0xc2, 0x65, 0xce, 0xb3, 0x66, 0x26, 0x37, 0xb2, 0x6f, 0x7c,
	0x0b, 0x23, 0xa9, 0x62, 0xae, 0x85, 0xca, 0xcf, 0xeb, 0x1c, 0x28, 0xc1, 0x1a, 0xdc, 0xa8, 0xce,
	0x7e, 0x53, 0xfa, 0xb4, 0x96, 0x3d, 0x58, 0x8b, 0x1e, 0x5c, 0x67, 0x54, 0x55, 0x3c, 0x6d, 0x16,
	0x77, 0xa3, 0x2e, 0x0c, 0xfe, 0x32, 0x98, 0x58, 0xd9, 0x1f, 0x26, 0xcb, 0x78, 0xf9, 0x1b, 0x5f,
	0xc1, 0xb8, 0xa8, 0xab, 0x37, 0xb1, 0x32, 0xb9, 0x6e, 0x4d, 0x04, 0x0b, 0x7d, 0xae, 0x11, 0x7c,
	0x03, 0x4f, 0xb6, 0xcd, 0x56, 0x2d, 0xa5, 0xb1, 0x72, 0xd2, 0x82, 0x0d, 0xc9, 0x87, 0x51, 0x22,
	0x2a, 0xcd, 0xf3, 0x98, 0xbc, 0x47, 0xcd, 0x1d, 0xba, 0x18, 0x6f, 0x60, 0x42, 0x92, 0x17, 0x15,
	0x25, 0x1b, 0x2d, 0x32, 0xf2, 0x2e, 0x6d, 0x7e, 0xdc, 0x62, 0x6b, 0x91, 0xd1, 0xdd, 0x1f, 0x07,
	0xc0, 0x4e, 0xb5, 0xac, 0xd7, 0xc1, 0xf7, 0x00, 0x4b, 0xd2, 0x9d, 0x97, 0xff, 0x6f, 0xea, 0x3f,
	0xeb, 0x43, 0x2d, 0x2f, 0xb8, 0xc0, 0x0f, 0x00, 0x5f, 0xb8, 0xdc, 0xce, 0x4d, 0x21, 0x69, 0x8f,
	0xcf, 0xfb, 0xa4, 0xc3, 0xad, 0xcf, 0xd4, 0xce, 0x18, 0xce, 0x61, 0x1a, 0xd1, 0x2f, 0x2a, 0x2b,
	0xea, 0x89, 0x0c, 0x34, 0xf7, 0x4e, 0x74, 0x7b, 0x5e, 0x06, 0x17, 0xb7, 0x0c, 0x3f, 0x02, 0x2c,
	0x8c, 0x94, 0x83, 0x33, 0x74, 0xe7, 0xf4, 0x87, 0xe1, 0xba, 0x7e, 0xc6, 0xee, 0x67, 0xf0, 0x42,
	0xa8, 0x30, 0x2d, 0x8b, 0x38, 0xa4, 0x3d, 0xcf, 0x0a, 0x49, 0x55, 0x8f, 0x7e, 0xff, 0xf4, 0x68,
	0xd4, 0xaa, 0xfe, 0x18, 0x2b, 0xf6, 0xf3, 0xb1, 0xfd, 0x21, 0xef, 0xfe, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x58, 0x62, 0x34, 0xfa, 0x36, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouteGuideClient is the client API for RouteGuide service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouteGuideClient interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetFeature(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Feature, error)
	// A server-to-client streaming RPC.
	//
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	HalfDuplex(ctx context.Context, in *Rectangle, opts ...grpc.CallOption) (RouteGuide_HalfDuplexClient, error)
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	ReverseHalfDuplex(ctx context.Context, opts ...grpc.CallOption) (RouteGuide_ReverseHalfDuplexClient, error)
	// A Bidirectional streaming RPC.
	//
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	FullDuplex(ctx context.Context, opts ...grpc.CallOption) (RouteGuide_FullDuplexClient, error)
}

type routeGuideClient struct {
	cc *grpc.ClientConn
}

func NewRouteGuideClient(cc *grpc.ClientConn) RouteGuideClient {
	return &routeGuideClient{cc}
}

func (c *routeGuideClient) GetFeature(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Feature, error) {
	out := new(Feature)
	err := c.cc.Invoke(ctx, "/routeguide.RouteGuide/GetFeature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeGuideClient) HalfDuplex(ctx context.Context, in *Rectangle, opts ...grpc.CallOption) (RouteGuide_HalfDuplexClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RouteGuide_serviceDesc.Streams[0], "/routeguide.RouteGuide/HalfDuplex", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeGuideHalfDuplexClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RouteGuide_HalfDuplexClient interface {
	Recv() (*Feature, error)
	grpc.ClientStream
}

type routeGuideHalfDuplexClient struct {
	grpc.ClientStream
}

func (x *routeGuideHalfDuplexClient) Recv() (*Feature, error) {
	m := new(Feature)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *routeGuideClient) ReverseHalfDuplex(ctx context.Context, opts ...grpc.CallOption) (RouteGuide_ReverseHalfDuplexClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RouteGuide_serviceDesc.Streams[1], "/routeguide.RouteGuide/ReverseHalfDuplex", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeGuideReverseHalfDuplexClient{stream}
	return x, nil
}

type RouteGuide_ReverseHalfDuplexClient interface {
	Send(*Point) error
	CloseAndRecv() (*RouteSummary, error)
	grpc.ClientStream
}

type routeGuideReverseHalfDuplexClient struct {
	grpc.ClientStream
}

func (x *routeGuideReverseHalfDuplexClient) Send(m *Point) error {
	return x.ClientStream.SendMsg(m)
}

func (x *routeGuideReverseHalfDuplexClient) CloseAndRecv() (*RouteSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RouteSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *routeGuideClient) FullDuplex(ctx context.Context, opts ...grpc.CallOption) (RouteGuide_FullDuplexClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RouteGuide_serviceDesc.Streams[2], "/routeguide.RouteGuide/FullDuplex", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeGuideFullDuplexClient{stream}
	return x, nil
}

type RouteGuide_FullDuplexClient interface {
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc.ClientStream
}

type routeGuideFullDuplexClient struct {
	grpc.ClientStream
}

func (x *routeGuideFullDuplexClient) Send(m *RouteNote) error {
	return x.ClientStream.SendMsg(m)
}

func (x *routeGuideFullDuplexClient) Recv() (*RouteNote, error) {
	m := new(RouteNote)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RouteGuideServer is the server API for RouteGuide service.
type RouteGuideServer interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetFeature(context.Context, *Point) (*Feature, error)
	// A server-to-client streaming RPC.
	//
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	HalfDuplex(*Rectangle, RouteGuide_HalfDuplexServer) error
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	ReverseHalfDuplex(RouteGuide_ReverseHalfDuplexServer) error
	// A Bidirectional streaming RPC.
	//
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	FullDuplex(RouteGuide_FullDuplexServer) error
}

// UnimplementedRouteGuideServer can be embedded to have forward compatible implementations.
type UnimplementedRouteGuideServer struct {
}

func (*UnimplementedRouteGuideServer) GetFeature(ctx context.Context, req *Point) (*Feature, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeature not implemented")
}
func (*UnimplementedRouteGuideServer) HalfDuplex(req *Rectangle, srv RouteGuide_HalfDuplexServer) error {
	return status.Errorf(codes.Unimplemented, "method HalfDuplex not implemented")
}
func (*UnimplementedRouteGuideServer) ReverseHalfDuplex(srv RouteGuide_ReverseHalfDuplexServer) error {
	return status.Errorf(codes.Unimplemented, "method ReverseHalfDuplex not implemented")
}
func (*UnimplementedRouteGuideServer) FullDuplex(srv RouteGuide_FullDuplexServer) error {
	return status.Errorf(codes.Unimplemented, "method FullDuplex not implemented")
}

func RegisterRouteGuideServer(s *grpc.Server, srv RouteGuideServer) {
	s.RegisterService(&_RouteGuide_serviceDesc, srv)
}

func _RouteGuide_GetFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Point)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteGuideServer).GetFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routeguide.RouteGuide/GetFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteGuideServer).GetFeature(ctx, req.(*Point))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteGuide_HalfDuplex_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Rectangle)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RouteGuideServer).HalfDuplex(m, &routeGuideHalfDuplexServer{stream})
}

type RouteGuide_HalfDuplexServer interface {
	Send(*Feature) error
	grpc.ServerStream
}

type routeGuideHalfDuplexServer struct {
	grpc.ServerStream
}

func (x *routeGuideHalfDuplexServer) Send(m *Feature) error {
	return x.ServerStream.SendMsg(m)
}

func _RouteGuide_ReverseHalfDuplex_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RouteGuideServer).ReverseHalfDuplex(&routeGuideReverseHalfDuplexServer{stream})
}

type RouteGuide_ReverseHalfDuplexServer interface {
	SendAndClose(*RouteSummary) error
	Recv() (*Point, error)
	grpc.ServerStream
}

type routeGuideReverseHalfDuplexServer struct {
	grpc.ServerStream
}

func (x *routeGuideReverseHalfDuplexServer) SendAndClose(m *RouteSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *routeGuideReverseHalfDuplexServer) Recv() (*Point, error) {
	m := new(Point)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RouteGuide_FullDuplex_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RouteGuideServer).FullDuplex(&routeGuideFullDuplexServer{stream})
}

type RouteGuide_FullDuplexServer interface {
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc.ServerStream
}

type routeGuideFullDuplexServer struct {
	grpc.ServerStream
}

func (x *routeGuideFullDuplexServer) Send(m *RouteNote) error {
	return x.ServerStream.SendMsg(m)
}

func (x *routeGuideFullDuplexServer) Recv() (*RouteNote, error) {
	m := new(RouteNote)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RouteGuide_serviceDesc = grpc.ServiceDesc{
	ServiceName: "routeguide.RouteGuide",
	HandlerType: (*RouteGuideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeature",
			Handler:    _RouteGuide_GetFeature_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HalfDuplex",
			Handler:       _RouteGuide_HalfDuplex_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReverseHalfDuplex",
			Handler:       _RouteGuide_ReverseHalfDuplex_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FullDuplex",
			Handler:       _RouteGuide_FullDuplex_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "route_guide.proto",
}
